### PR TITLE
Some useful working enhancements

### PR DESCRIPTION
**Pull request by Alberto96**
Full tested. Kernel boots and works without any problem. Compiled with same toolchain (linaro gcc 4.8.2)

Dynamic FSync needs more work and i reverted it.

I'm running kernel with this changes and for me works smoother than before. No SODs or Crashes.

### CODE REVIEW

**Comment by AndreiLux** [comment]
Some of these commits are utter nonsense.

I'll go over them later today.

**Comment by Alberto96** [comment]
Yeh, i know. Not all are useful. I'm using most of this commits also on my Galaxy S Kernel so i added them to perseus.

**Comment by AndreiLux** [comment]
I pulled what was meaningful into the kernel. Next time spare me all the other trash.

**Comment by Alberto96** [comment]
No problem ;)

**Pull request closed without merging**
